name: semipar
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=24.0 
  - pandas=2.2.2
  - pyarrow=17.0.0
  - polars=1.5.0
  - pyGAM=0.9.1
  - scikit-sparse=0.4.14
  - nose=1.3.7
  - sqlmodel=0.0.22
  - ibis-postgres=9.5.0
  - ibis-sqlite=9.5.0
  - tqdm=4.67.0