[project]
name = "pr-salaries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "altair[all]>=5.5.0",
  "duckdb>=1.1.3",
  "geopandas>=1.0.1",
  "matplotlib>=3.10.0",
  "pandas>=2.2.3",
  "polars>=1.16.0",
  "pysal>=5.1",
  "tqdm>=4.67.1",
  "segregation>=2.5.2",
  "llvmlite>=0.44.0",
  "numba>=0.61.0",
  "arviz[all]>=0.21.0",
  "bambi>=0.15.0",
  "causalpy>=0.4.0",
]

[dependency-groups]
dev = [
    "gcsfs>=2024.12.0",
    "jupyter>=1.1.1",
    "pins>=0.8.7",
    "pynvim>=0.5.2",
]
