[project]
name = "pr-salaries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "duckdb>=1.1.3",
  "geopandas>=1.0.1",
  "matplotlib>=3.10.0",
  "pandas>=2.2.3",
  "polars>=1.16.0",
  "pysal>=5.1",
  "tqdm>=4.67.1",
  "arviz[all]>=0.21.0",
  "bambi>=0.15.0",
  "linearmodels>=6.1",
  "pyarrow>=20.0.0",
  "ruff>=0.11.10",
  "python-dotenv>=1.1.0",
  "numpyro>=0.18.0",
  "nutpie>=0.14.3",
]

[dependency-groups]
dev = ["jupyter>=1.1.1", "nutpie>=0.14.3", "pre-commit>=4.2.0", "pynvim>=0.5.2"]
