[project]
name = "pr-salaries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "duckdb>=1.1.3",
  "geopandas>=1.0.1",
  "ibis-framework[duckdb,geospatial]>=9.5.0",
  "matplotlib>=3.10.0",
  "pandas>=2.2.3",
  "polars>=1.16.0",
  "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "gcsfs>=2024.12.0",
    "jupyter>=1.1.1",
    "pins>=0.8.7",
    "pynvim>=0.5.2",
]
